name: law-example
channels:
  - default
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - numpy
  - pandas
  - ipython
  - pip:
    - git+https://github.com/riga/law.git # install law from github since we need pandas formatter
